# Laptop internal
# 1366x768@59.97700 at 0x0
monitor = eDP-1, 1366x768, 0x0, 1

# Monitor Configuration
# See Hyprland wiki for more details
# https://wiki.hyprland.org/Configuring/Monitors/
# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

# Monitor DVI-D-1 (ID 0):
#         1920x1080@60.00000 at 0x0
# Monitor HDMI-A-1 (ID 1):
#         1920x1080@60.00000 at 1920x0
# Monitors
monitor = HDMI-A-1, 1920x1080, 0x0, 1
monitor = DVI-D-1, 1920x1080, 1920x0, 1
input:tablet:output = DVI-D-1
# All workspaces on main monitor, except for 10 for tablet

workspace = 1, monitor:HDMI-A-1, persistent:true, default:true
workspace = 2, monitor:HDMI-A-1, persistent:true
workspace = 3, monitor:HDMI-A-1, persistent:true
workspace = 4, monitor:HDMI-A-1, persistent:true
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true
workspace = 9, monitor:HDMI-A-1, persistent:true

workspace = 10, monitor:DVI-D-1, persistent:true, default:true
# Catch-all for any other displays
monitor = , preferred, auto, 1
