# Laptop internal
monitor = eDP-1, preferred, auto, 2

# PC dual monitors
monitor = DP-1, 2560x1440@144, 0x0, 1
monitor = DP-2, 1920x1080@144, 2560x0, 1

# Catch-all for any other displays
monitor = , preferred, auto, 1
