
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.7
padding = {}

[font]
size = 12
[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[general]
live_config_reload = true
import = [
  # "/usr/lib/node_modules/alacritty-themes/themes/Challenger-Deep.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
]
# [font.bold]
# family = "Roboto Mono Nerd Font"
# style = "Heavy"
#
# [font.bold_italic]
# family = "Roboto Mono Nerd Font"
# style = "Heavy Italic"
#
# [font.italic]
# family = "Roboto Mono Nerd Font"
# style = "Medium Italic"
#
# [font.normal]
# family = "Roboto Mono Nerd Font"
# style = "Medium"

# [shell]
# program = "tmux"
